# Generated by Django 4.0.3 on 2022-03-20 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shedule.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='code_conference',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
